apiVersion: v1
appVersion: "0.2.3"
description: A Helm chart for Kubernetes
name: squid
version: "0.1.0"
home: https://github.com/pacroy/squid
keywords:
- squid
- proxy
maintainers:
- email: pacroy@gmail.com
  name: Par
sources:
- https://github.com/pacroy/squid
